import {reviewQuestions as questions,counts} from './questions.mjs';
import {sourceLabels,responseSource,filterBySource} from './source.mjs';
import {escape as e} from './core.mjs';
const app=document.querySelector('#app'),notice=document.querySelector('#notice'),cfg=window.RESEARCH_CONFIG||{};let token='',allRows=[],sourceFilter='all';
const ready=/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(cfg.url||'')&&cfg.publishableKey;
function login(){app.innerHTML='<div class="narrow"><h1>Antworten auswerten</h1>'+(ready?'<form id="login" class="card"><label for="email">E-Mail</label><input id="email" type="email" autocomplete="username" required><label for="password">Passwort</label><input id="password" type="password" autocomplete="current-password" required><div class="actions"><button class="primary">Anmelden</button></div></form>':'<p>Die Datenbank ist noch nicht verbunden. Hier wird nach der Einrichtung die geschützte Auswertung angezeigt.</p>')+'</div>';document.querySelector('#login')?.addEventListener('submit',async ev=>{ev.preventDefault();const btn=ev.target.querySelector('button');btn.disabled=true;try{const res=await fetch(cfg.url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:cfg.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email:document.querySelector('#email').value,password:document.querySelector('#password').value})});if(!res.ok)throw Error('Anmeldung fehlgeschlagen.');token=(await res.json()).access_token;await load();}catch(err){notice.textContent=err.message;btn.disabled=false;}});}
async function get(path){const res=await fetch(cfg.url+'/rest/v1/'+path,{headers:{apikey:cfg.publishableKey,Authorization:'Bearer '+token}});if(!res.ok)throw Error('Zugriff fehlgeschlagen. Bitte erneut anmelden oder Freigabe prüfen.');return res.json();}
async function load(){const members=await get('research_members?select=user_id');if(!members.length)throw Error('Dieses Konto ist nicht für die Auswertung freigegeben.');allRows=await get('research_responses?select=*&order=created_at.desc&limit=1000');notice.textContent='';document.querySelector('#logout').hidden=false;render();}
function answerText(a){return [a?.otherText,a?.text].filter(Boolean).join('\n\n');}
function bars(values,n){return values.map(([label,count])=>`<div class="row between"><span>${e(label)}</span><strong>${count} / ${n}</strong></div><div class="bar"><span style="width:${count/Math.max(n,1)*100}%"></span></div>`).join('');}
function render(){const rows=filterBySource(allRows,sourceFilter);app.innerHTML=`<h1>${rows.length} Antworten</h1><label for="source-filter">Herkunft filtern</label><select id="source-filter">${Object.entries({all:'Alle Antworten',...sourceLabels}).map(([value,label])=>`<option value="${value}" ${sourceFilter===value?'selected':''}>${e(label)}</option>`).join('')}</select><p class="muted">Die Herkunft wird über den verwendeten Link erfasst, nicht über die Person. Weitergeleitete Links behalten ihre Kennzeichnung. Frühere Antworten stehen unter „Direkt / unbekannt“.</p><p class="banner">Eine kleine, selbst ausgewählte Stichprobe. Die Zahlen zeigen erste Muster, keine repräsentativen Aussagen über alle Mietinteressenten. Mehrfachauswahlen können sich auf mehr als 100 % summieren.</p><div class="actions"><button id="refresh">Aktualisieren</button><button id="export">JSON exportieren</button><a class="button" href="/research">Formular öffnen</a><p>Einladungslink: https://www.bashkaran.ch/research?source=invitation</p></div><div id="invite-output" class="invite-output" role="status"></div>${questions.map(q=>{const n=rows.filter(r=>r.payload.answers[q.id]?.values.length).length;return `<section class="card"><h2>${e(q.title)}</h2>${q.options?`<p class="muted">${n} beantwortet · ${rows.length-n} ohne Auswahl</p>${bars(counts(rows,q),n)}`:''}<details><summary>Originalaussagen ansehen</summary>${rows.filter(r=>answerText(r.payload.answers[q.id])).map(r=>`<p class="quote"><small>Antwort ${e(r.id.slice(0,8))}</small><br>${e(answerText(r.payload.answers[q.id]))}</p>`).join('')||'<p>Keine Freitextantworten.</p>'}</details></section>`;}).join('')}<section class="card"><h2>Einzelne Antworten</h2>${rows.map(r=>`<details><summary>${e(new Date(r.created_at).toLocaleDateString('de-CH'))} · ${e(r.id.slice(0,8))} · ${e(sourceLabels[responseSource(r)])}</summary>${questions.map(q=>`<h3>${e(q.title)}</h3><p>${e(r.payload.answers[q.id]?.values.join(', ')||'Keine Auswahl')}</p><p class="quote">${e(answerText(r.payload.answers[q.id])||'')}</p>`).join('')}</details>`).join('')}</section>`;document.querySelector('#source-filter').onchange=ev=>{sourceFilter=ev.target.value;render();};document.querySelector('#refresh').onclick=()=>load().catch(err=>notice.textContent=err.message);document.querySelector('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({questions,responses:rows.map(r=>({id:r.id,created_at:r.created_at,payload:{version:r.payload.version,consent:r.payload.consent,source:responseSource(r),language:r.payload.language||'de',answers:r.payload.answers}}))},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='befragung.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};}
document.querySelector('#logout').onclick=async()=>{try{await fetch(cfg.url+'/auth/v1/logout',{method:'POST',headers:{apikey:cfg.publishableKey,Authorization:'Bearer '+token}});}finally{token='';allRows=[];document.querySelector('#logout').hidden=true;notice.textContent='';login();}};
login();
