import {questions,validate} from './questions.mjs';
import {escape as e} from './core.mjs';
const app=document.querySelector('#app'),notice=document.querySelector('#notice'),cfg=window.RESEARCH_CONFIG||{};
const ready=/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(cfg.url||'')&&!!cfg.publishableKey&&cfg.submissionsEnabled===true;
const payload={version:2,consent:false,answers:Object.fromEntries(questions.map(q=>[q.id,{values:[],text:''}]))};
let step=0,sending=false,changed=false;const submissionId=crypto.randomUUID();
if(!ready)notice.textContent='Vorschau: Die Speicherung wird noch eingerichtet. Absenden ist noch nicht freigegeben.';
window.addEventListener('beforeunload',ev=>{if(changed){ev.preventDefault();ev.returnValue='';}});
function question(q){const a=payload.answers[q.id];return `<fieldset class="card"><legend>${e(q.title)}</legend>${q.options?`<p class="muted">${q.multi?'Mehrfachauswahl möglich':'Eine Antwort möglich'}</p><div class="choices">${q.options.map((o,i)=>`<label class="choice"><input type="${q.multi?'checkbox':'radio'}" name="${q.id}" value="${e(o)}" ${a.values.includes(o)?'checked':''}>${e(o)}</label>`).join('')}</div>`:''}${q.free?`<label for="${q.id}-text">${e(q.free)}</label><textarea class="notes" id="${q.id}-text" name="${q.id}-text" maxlength="3000">${e(a.text)}</textarea>`:''}</fieldset>`;}
function render(){
 const group=step===0?questions.slice(0,3):questions.slice(3);
 app.innerHTML=`<div class="narrow"><h1>Deine Erfahrung zählt.</h1><p>Was läuft bei der Wohnungssuche gut – und was ist mühsam? Mit deinen Antworten hilfst du uns, den Mietprozess besser zu verstehen.</p><p class="muted">Jede Frage ist freiwillig – du kannst Fragen überspringen. Deine Teilnahme hat keinen Einfluss auf eine Wohnungsbewerbung. Wir fragen weder Namen noch E-Mail-Adressen ab. Bitte nenne auch in Freitexten keine persönlichen Daten.</p><p class="eyebrow">${['1 / 3 · Wohnungssuche','2 / 3 · Bewerbung & Erfahrungen','3 / 3 · Absenden'][step]}</p><form id="survey">${step<2?group.map(question).join(''):`<section class="card"><h2>Antworten absenden</h2><p>Vielen Dank für deine Erfahrungen. Über „Zurück“ kannst du deine Antworten nochmals prüfen.</p></section><label class="check"><input type="checkbox" id="consent" ${payload.consent?'checked':''}>Ich stimme zu, dass Bashkaran Real Estate meine Antworten für die interne Auswertung dieser Befragung speichert. Hinweise zum Umgang mit Daten stehen in der <a href="/datenschutz.html" target="_blank" rel="noopener">Datenschutzerklärung</a>.</label>`}<div class="actions">${step?'<button type="button" id="previous">Zurück</button>':''}<button class="primary" ${step===2&&!ready?'disabled':''}>${step===2?'Antworten senden':'Weiter'}</button></div>${step===2?'<p class="muted">Es wird erst beim Absenden gespeichert. </p>':''}</form></div>`;
 document.querySelector('#previous')?.addEventListener('click',()=>{capture();step--;render();window.scrollTo(0,0);});
 document.querySelector('#survey').addEventListener('input',ev=>{changed=true;const q=questions.find(q=>q.id===ev.target.name);if(q?.multi&&ev.target.checked){const ex=[q.exclusive].flat();document.querySelectorAll(`input[name="${q.id}"]`).forEach(el=>{if(el!==ev.target&&(ex.includes(ev.target.value)||ex.includes(el.value)))el.checked=false;});}});
 document.querySelector('#survey').addEventListener('submit',async ev=>{ev.preventDefault();if(sending)return;capture();if(step<2){step++;render();window.scrollTo(0,0);return;}if(!payload.consent){notice.textContent='Bitte bestätige die Zustimmung vor dem Absenden.';notice.scrollIntoView();return;}if(!validate(payload)){notice.textContent='Bitte prüfe deine Eingaben.';return;}if(!ready)return;sending=true;const btn=ev.submitter;btn.disabled=true;btn.textContent='Wird gesendet …';try{const res=await fetch('/api/research-submit',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({submission:submissionId,answer:payload})});if(!res.ok)throw Error();const receipt=await res.json();if(receipt!==submissionId)throw Error();changed=false;notice.textContent='';app.innerHTML='<div class="narrow card"><p class="eyebrow">Befragung abgeschlossen</p><h1>Vielen Dank!</h1><p>Deine Antworten wurden gespeichert. Du kannst dieses Fenster jetzt schliessen.</p></div>';}catch{notice.textContent='Die Antworten konnten nicht gesendet werden. Deine Eingaben bleiben in diesem geöffneten Fenster erhalten. Bitte versuche es erneut.';btn.disabled=false;btn.textContent='Erneut senden';}finally{sending=false;}});
}
function capture(){if(step===2){payload.consent=document.querySelector('#consent').checked;return;}for(const q of (step===0?questions.slice(0,3):questions.slice(3))){payload.answers[q.id]={values:[...document.querySelectorAll(`input[name="${q.id}"]:checked`)].map(el=>el.value),text:document.querySelector(`#${q.id}-text`)?.value||''};}}
render();
